/*
 * Copyright 2021 Nikola Trubitsyn
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.trubitsyn.carbonnowsh

object Languages {
    private const val APPLICATION_SLASH_JSON = "application/json"
    private const val APPLICATION_SLASH_N_MINUS_TRIPLES = "application/n-triples"
    private const val APPLICATION_SLASH_SPARQL_MINUS_QUERY = "application/sparql-query"
    private const val APPLICATION_SLASH_TYPESCRIPT = "application/typescript"
    private const val APPLICATION_SLASH_X_MINUS_SH = "application/x-sh"
    private const val AUTO = "auto"
    private const val CLOJURE = "clojure"
    private const val COBOL = "cobol"
    private const val COFFEESCRIPT = "coffeescript"
    private const val CRYSTAL = "crystal"
    private const val CSS = "css"
    private const val D = "d"
    private const val DART = "dart"
    private const val ELIXIR = "elixir"
    private const val ELM = "elm"
    private const val ERLANG = "erlang"
    private const val FORTRAN = "fortran"
    private const val GHERKIN = "gherkin"
    private const val GRAPHQL = "graphql"
    private const val GROOVY = "groovy"
    private const val HANDLEBARS = "handlebars"
    private const val HASKELL = "haskell"
    private const val HTMLMIXED = "htmlmixed"
    private const val JAVASCRIPT = "javascript"
    private const val JSX = "jsx"
    private const val JULIA = "julia"
    private const val LUA = "lua"
    private const val MATHEMATICA = "mathematica"
    private const val MLLIKE = "mllike"
    private const val NGINX = "nginx"
    private const val NIM = "nim"
    private const val PASCAL = "pascal"
    private const val PERL = "perl"
    private const val POWERSHELL = "powershell"
    private const val PYTHON = "python"
    private const val R = "r"
    private const val RUBY = "ruby"
    private const val RUST = "rust"
    private const val SASS = "sass"
    private const val SMALLTALK = "smalltalk"
    private const val SQL = "sql"
    private const val STYLUS = "stylus"
    private const val SWIFT = "swift"
    private const val TCL = "tcl"
    private const val TEXT_SLASH_TURTLE = "text/turtle"
    private const val TEXT_SLASH_TYPESCRIPT_MINUS_JSX = "text/typescript-jsx"
    private const val TEXT_SLASH_X_MINUS_CSHARP = "text/x-csharp"
    private const val TEXT_SLASH_X_MINUS_CSRC = "text/x-csrc"
    private const val TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC = "text/x-c++src"
    private const val TEXT_SLASH_X_MINUS_DIFF = "text/x-diff"
    private const val TEXT_SLASH_X_MINUS_GO = "text/x-go"
    private const val TEXT_SLASH_X_MINUS_JAVA = "text/x-java"
    private const val TEXT_SLASH_X_MINUS_KOTLIN = "text/x-kotlin"
    private const val TEXT_SLASH_X_MINUS_OCTAVE = "text/x-octave"
    private const val TEXT_SLASH_X_MINUS_PHP = "text/x-php"
    private const val TEXT_SLASH_X_MINUS_SCALA = "text/x-scala"
    private const val TEXT_SLASH_X_MINUS_TWIG = "text/x-twig"
    private const val TOML = "toml"
    private const val VERILOG = "verilog"
    private const val VHDL = "vhdl"
    private const val VUE = "vue"
    private const val XQUERY = "xquery"
    private const val YAML = "yaml"

    private val mapping = hashMapOf(
        "_coffee" to COFFEESCRIPT,
        "_js" to JAVASCRIPT,
        "adml" to HTMLMIXED,
        "admx" to HTMLMIXED,
        "adp" to TCL,
        "al" to PERL,
        "ant" to HTMLMIXED,
        "app.src" to ERLANG,
        "avsc" to APPLICATION_SLASH_JSON,
        "aw" to TEXT_SLASH_X_MINUS_PHP,
        "axml" to HTMLMIXED,
        "bones" to JAVASCRIPT,
        "boot" to CLOJURE,
        "builder" to RUBY,
        "builds" to HTMLMIXED,
        "c" to TEXT_SLASH_X_MINUS_CSRC,
        "c++" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "cake" to TEXT_SLASH_X_MINUS_CSHARP,
        "cake" to COFFEESCRIPT,
        "cats" to TEXT_SLASH_X_MINUS_CSRC,
        "cbl" to COBOL,
        "cc" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "ccp" to COBOL,
        "ccproj" to HTMLMIXED,
        "ccxml" to HTMLMIXED,
        "cdf" to MATHEMATICA,
        "cgi" to PERL,
        "cgi" to PYTHON,
        "cjs" to JAVASCRIPT,
        "cjsx" to COFFEESCRIPT,
        "cl2" to CLOJURE,
        "clixml" to HTMLMIXED,
        "clj" to CLOJURE,
        "cljc" to CLOJURE,
        "cljs" to CLOJURE,
        "cljs.hl" to CLOJURE,
        "cljscm" to CLOJURE,
        "cljx" to CLOJURE,
        "cob" to COBOL,
        "cobol" to COBOL,
        "coffee" to COFFEESCRIPT,
        "cp" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "cpp" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "cproject" to HTMLMIXED,
        "cpy" to COBOL,
        "cql" to SQL,
        "cr" to CRYSTAL,
        "cs" to TEXT_SLASH_X_MINUS_CSHARP,
        "cs" to SMALLTALK,
        "cscfg" to HTMLMIXED,
        "csdef" to HTMLMIXED,
        "csl" to HTMLMIXED,
        "csproj" to HTMLMIXED,
        "css" to CSS,
        "csx" to TEXT_SLASH_X_MINUS_CSHARP,
        "ct" to HTMLMIXED,
        "ctp" to TEXT_SLASH_X_MINUS_PHP,
        "cxx" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "d" to D,
        "dart" to DART,
        "ddl" to SQL,
        "depproj" to HTMLMIXED,
        "dfm" to PASCAL,
        "di" to D,
        "diff" to TEXT_SLASH_X_MINUS_DIFF,
        "dita" to HTMLMIXED,
        "ditamap" to HTMLMIXED,
        "ditaval" to HTMLMIXED,
        "dll.config" to HTMLMIXED,
        "dotsettings" to HTMLMIXED,
        "dpr" to PASCAL,
        "eliom" to MLLIKE,
        "eliomi" to MLLIKE,
        "elm" to ELM,
        "erl" to ERLANG,
        "es" to ERLANG,
        "es" to JAVASCRIPT,
        "es6" to JAVASCRIPT,
        "escript" to ERLANG,
        "ex" to ELIXIR,
        "exs" to ELIXIR,
        "eye" to RUBY,
        "f" to FORTRAN,
        "f77" to FORTRAN,
        "fcgi" to LUA,
        "fcgi" to PERL,
        "fcgi" to TEXT_SLASH_X_MINUS_PHP,
        "fcgi" to PYTHON,
        "fcgi" to RUBY,
        "feature" to GHERKIN,
        "filters" to HTMLMIXED,
        "for" to FORTRAN,
        "fpp" to FORTRAN,
        "frag" to JAVASCRIPT,
        "fs" to MLLIKE,
        "fsi" to MLLIKE,
        "fsproj" to HTMLMIXED,
        "fsx" to MLLIKE,
        "fxml" to HTMLMIXED,
        "gemspec" to RUBY,
        "geojson" to APPLICATION_SLASH_JSON,
        "glade" to HTMLMIXED,
        "gltf" to APPLICATION_SLASH_JSON,
        "gml" to HTMLMIXED,
        "gmx" to HTMLMIXED,
        "go" to TEXT_SLASH_X_MINUS_GO,
        "god" to RUBY,
        "gql" to GRAPHQL,
        "graphql" to GRAPHQL,
        "graphqls" to GRAPHQL,
        "groovy" to GROOVY,
        "grt" to GROOVY,
        "grxml" to HTMLMIXED,
        "gs" to JAVASCRIPT,
        "gtpl" to GROOVY,
        "gvy" to GROOVY,
        "gyp" to PYTHON,
        "gypi" to PYTHON,
        "h" to TEXT_SLASH_X_MINUS_CSRC,
        "h" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "h++" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "handlebars" to HANDLEBARS,
        "har" to APPLICATION_SLASH_JSON,
        "hbs" to HANDLEBARS,
        "hh" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "hic" to CLOJURE,
        "hpp" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "hrl" to ERLANG,
        "hs" to HASKELL,
        "hs-boot" to HASKELL,
        "hsc" to HASKELL,
        "htm" to HTMLMIXED,
        "html" to HTMLMIXED,
        "html.hl" to HTMLMIXED,
        "hxx" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "ice" to APPLICATION_SLASH_JSON,
        "iced" to COFFEESCRIPT,
        "idc" to TEXT_SLASH_X_MINUS_CSRC,
        "iml" to HTMLMIXED,
        "inc" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "inc" to HTMLMIXED,
        "inc" to PASCAL,
        "inc" to TEXT_SLASH_X_MINUS_PHP,
        "inc" to SQL,
        "inl" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "ino" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "ipp" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "ivy" to HTMLMIXED,
        "jake" to JAVASCRIPT,
        "java" to TEXT_SLASH_X_MINUS_JAVA,
        "jbuilder" to RUBY,
        "jelly" to HTMLMIXED,
        "jl" to JULIA,
        "js" to JAVASCRIPT,
        "jsb" to JAVASCRIPT,
        "jscad" to JAVASCRIPT,
        "jsfl" to JAVASCRIPT,
        "jsm" to JAVASCRIPT,
        "json" to APPLICATION_SLASH_JSON,
        "json" to APPLICATION_SLASH_JSON,
        "JSON-tmLanguage" to APPLICATION_SLASH_JSON,
        "jsonl" to APPLICATION_SLASH_JSON,
        "jsproj" to HTMLMIXED,
        "jss" to JAVASCRIPT,
        "jsx" to JSX,
        "kml" to HTMLMIXED,
        "kojo" to TEXT_SLASH_X_MINUS_SCALA,
        "kt" to TEXT_SLASH_X_MINUS_KOTLIN,
        "ktm" to TEXT_SLASH_X_MINUS_KOTLIN,
        "kts" to TEXT_SLASH_X_MINUS_KOTLIN,
        "launch" to HTMLMIXED,
        "linq" to TEXT_SLASH_X_MINUS_CSHARP,
        "lmi" to PYTHON,
        "lpr" to PASCAL,
        "lua" to LUA,
        "m" to MATHEMATICA,
        "m" to TEXT_SLASH_X_MINUS_OCTAVE,
        "ma" to MATHEMATICA,
        "map" to APPLICATION_SLASH_JSON,
        "mathematica" to MATHEMATICA,
        "matlab" to TEXT_SLASH_X_MINUS_OCTAVE,
        "mcmeta" to APPLICATION_SLASH_JSON,
        "mdpolicy" to HTMLMIXED,
        "mir" to YAML,
        "mjml" to HTMLMIXED,
        "mjs" to JAVASCRIPT,
        "ml" to MLLIKE,
        "ml4" to MLLIKE,
        "mli" to MLLIKE,
        "mll" to MLLIKE,
        "mly" to MLLIKE,
        "mm" to HTMLMIXED,
        "mod" to HTMLMIXED,
        "mspec" to RUBY,
        "mt" to MATHEMATICA,
        "mxml" to HTMLMIXED,
        "mysql" to SQL,
        "natvis" to HTMLMIXED,
        "nb" to MATHEMATICA,
        "nbp" to MATHEMATICA,
        "ncl" to HTMLMIXED,
        "ndproj" to HTMLMIXED,
        "nginxconf" to NGINX,
        "nim" to NIM,
        "nim.cfg" to NIM,
        "nimble" to NIM,
        "nimrod" to NIM,
        "nims" to NIM,
        "njs" to JAVASCRIPT,
        "nproj" to HTMLMIXED,
        "nse" to LUA,
        "nt" to APPLICATION_SLASH_N_MINUS_TRIPLES,
        "nuspec" to HTMLMIXED,
        "odd" to HTMLMIXED,
        "osm" to HTMLMIXED,
        "p8" to LUA,
        "pac" to JAVASCRIPT,
        "pas" to PASCAL,
        "pascal" to PASCAL,
        "patch" to TEXT_SLASH_X_MINUS_DIFF,
        "pd_lua" to LUA,
        "perl" to PERL,
        "ph" to PERL,
        "php" to TEXT_SLASH_X_MINUS_PHP,
        "php3" to TEXT_SLASH_X_MINUS_PHP,
        "php4" to TEXT_SLASH_X_MINUS_PHP,
        "php5" to TEXT_SLASH_X_MINUS_PHP,
        "phps" to TEXT_SLASH_X_MINUS_PHP,
        "phpt" to TEXT_SLASH_X_MINUS_PHP,
        "pkgproj" to HTMLMIXED,
        "pl" to PERL,
        "pluginspec" to HTMLMIXED,
        "pluginspec" to RUBY,
        "plx" to PERL,
        "pm" to PERL,
        "podspec" to RUBY,
        "pp" to PASCAL,
        "prc" to SQL,
        "proj" to HTMLMIXED,
        "props" to HTMLMIXED,
        "ps1" to POWERSHELL,
        "ps1xml" to HTMLMIXED,
        "psc1" to HTMLMIXED,
        "psd1" to POWERSHELL,
        "psgi" to PERL,
        "psm1" to POWERSHELL,
        "pt" to HTMLMIXED,
        "py" to PYTHON,
        "py3" to PYTHON,
        "pyde" to PYTHON,
        "pyi" to PYTHON,
        "pyp" to PYTHON,
        "pyt" to PYTHON,
        "pyw" to PYTHON,
        "r" to R,
        "rabl" to RUBY,
        "rake" to RUBY,
        "rb" to RUBY,
        "rbi" to RUBY,
        "rbuild" to RUBY,
        "rbw" to RUBY,
        "rbx" to RUBY,
        "rbxs" to LUA,
        "rd" to R,
        "rdf" to HTMLMIXED,
        "re" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "reek" to YAML,
        "resx" to HTMLMIXED,
        "rockspec" to LUA,
        "rpy" to PYTHON,
        "rq" to APPLICATION_SLASH_SPARQL_MINUS_QUERY,
        "rq" to APPLICATION_SLASH_SPARQL_MINUS_QUERY,
        "rs" to RUST,
        "rs.in" to RUST,
        "rss" to HTMLMIXED,
        "rsx" to R,
        "ru" to RUBY,
        "ruby" to RUBY,
        "rviz" to YAML,
        "sass" to SASS,
        "sbt" to TEXT_SLASH_X_MINUS_SCALA,
        "sc" to TEXT_SLASH_X_MINUS_SCALA,
        "scala" to TEXT_SLASH_X_MINUS_SCALA,
        "sch" to HTMLMIXED,
        "scxml" to HTMLMIXED,
        "sfproj" to HTMLMIXED,
        "sh" to APPLICATION_SLASH_X_MINUS_SH,
        "shproj" to HTMLMIXED,
        "sjs" to JAVASCRIPT,
        "smk" to PYTHON,
        "sparql" to APPLICATION_SLASH_SPARQL_MINUS_QUERY,
        "spec" to PYTHON,
        "spec" to RUBY,
        "sql" to SQL,
        "srdf" to HTMLMIXED,
        "ssjs" to JAVASCRIPT,
        "st" to HTMLMIXED,
        "st" to SMALLTALK,
        "storyboard" to HTMLMIXED,
        "styl" to STYLUS,
        "sublime-snippet" to HTMLMIXED,
        "sublime-syntax" to YAML,
        "swift" to SWIFT,
        "syntax" to YAML,
        "t" to PERL,
        "tab" to SQL,
        "tac" to PYTHON,
        "targets" to HTMLMIXED,
        "tcc" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "tcl" to TCL,
        "tfstate" to APPLICATION_SLASH_JSON,
        "tfstate.backup" to APPLICATION_SLASH_JSON,
        "thor" to RUBY,
        "tm" to TCL,
        "tml" to HTMLMIXED,
        "toml" to TOML,
        "topojson" to APPLICATION_SLASH_JSON,
        "tpp" to TEXT_SLASH_X_MINUS_C_PLUS_PLUS_SRC,
        "ts" to HTMLMIXED,
        "ts" to APPLICATION_SLASH_TYPESCRIPT,
        "tsx" to HTMLMIXED,
        "tsx" to TEXT_SLASH_TYPESCRIPT_MINUS_JSX,
        "ttl" to TEXT_SLASH_TURTLE,
        "ttl" to TEXT_SLASH_TURTLE,
        "twig" to TEXT_SLASH_X_MINUS_TWIG,
        "udf" to SQL,
        "ui" to HTMLMIXED,
        "urdf" to HTMLMIXED,
        "ux" to HTMLMIXED,
        "v" to VERILOG,
        "vbproj" to HTMLMIXED,
        "vcxproj" to HTMLMIXED,
        "veo" to VERILOG,
        "vhd" to VHDL,
        "vhdl" to VHDL,
        "vhf" to VHDL,
        "vhi" to VHDL,
        "vho" to VHDL,
        "vhost" to NGINX,
        "vhs" to VHDL,
        "vht" to VHDL,
        "vhw" to VHDL,
        "viw" to SQL,
        "vsixmanifest" to HTMLMIXED,
        "vssettings" to HTMLMIXED,
        "vstemplate" to HTMLMIXED,
        "vue" to VUE,
        "vxml" to HTMLMIXED,
        "watchr" to RUBY,
        "webapp" to APPLICATION_SLASH_JSON,
        "webmanifest" to APPLICATION_SLASH_JSON,
        "wixproj" to HTMLMIXED,
        "wl" to MATHEMATICA,
        "wlt" to MATHEMATICA,
        "wlua" to LUA,
        "workflow" to HTMLMIXED,
        "wsdl" to HTMLMIXED,
        "wsf" to HTMLMIXED,
        "wsgi" to PYTHON,
        "wxi" to HTMLMIXED,
        "wxl" to HTMLMIXED,
        "wxs" to HTMLMIXED,
        "x3d" to HTMLMIXED,
        "xacro" to HTMLMIXED,
        "xaml" to HTMLMIXED,
        "xht" to HTMLMIXED,
        "xhtml" to HTMLMIXED,
        "xib" to HTMLMIXED,
        "xlf" to HTMLMIXED,
        "xliff" to HTMLMIXED,
        "xmi" to HTMLMIXED,
        "xml" to HTMLMIXED,
        "xml.dist" to HTMLMIXED,
        "xproj" to HTMLMIXED,
        "xpy" to PYTHON,
        "xq" to XQUERY,
        "xql" to XQUERY,
        "xqm" to XQUERY,
        "xquery" to XQUERY,
        "xqy" to XQUERY,
        "xrl" to ERLANG,
        "xsd" to HTMLMIXED,
        "xsjs" to JAVASCRIPT,
        "xsjslib" to JAVASCRIPT,
        "xspec" to HTMLMIXED,
        "xul" to HTMLMIXED,
        "yaml" to YAML,
        "yaml-tmlanguage" to YAML,
        "yaml.sed" to YAML,
        "yml" to YAML,
        "yml.mysql" to YAML,
        "yrl" to ERLANG,
        "yy" to APPLICATION_SLASH_JSON,
        "yyp" to APPLICATION_SLASH_JSON,
        "zcml" to HTMLMIXED
    )

    fun forExtension(extension: String?): String {
        if (extension == null) {
            return AUTO
        }
        return mapping[extension] ?: AUTO
    }
}